package com.modapi.main;

import java.util.Arrays;

import com.modapi.main.Server.CommonProxy;
import com.modapi.main.helper.LogHandler;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "Mod-API", version="3.0",name="Mod API Base")
public class Mod_Api {
	
	@SidedProxy
	(clientSide="com.modapi.main.Client.CombinedClientProxy", 
	serverSide="com.modapi.main.Server.DedicatedServerProxy")
	public static CommonProxy proxy;
	
	@Mod.Instance("Mod_Api")
	public static Mod_Api INSTANCE;
	
	public static LogHandler logger;
	@EventHandler
	public static void PreInit(FMLPreInitializationEvent event)
	{
		proxy.preInit();
	
		ModMetadata meta = event.getModMetadata();
		meta.autogenerated = false;
		meta.credits = "(C) Roborave, 2013-2014";
		meta.authorList = Arrays.asList("Roborave");
		meta.name = "Mod-API";
		meta.version = "2.0";
		meta.description = "API for My Mods.";
		
	}
	
	@EventHandler
	public static void Init(FMLInitializationEvent event)
	{
		proxy.load();
		
	}
	
	@EventHandler
	public static void PostInit(FMLPostInitializationEvent event)
	{
		proxy.postInit();
	}
}
